# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='assets/images'),
        ),
    ]
