# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170708_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
    ]
