# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-16 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import gameViewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameViewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_files',
            field=models.FileField(upload_to=gameViewer.models.get_upload_path),
        ),
    ]
