# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import gameViewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameViewer', '0002_auto_20180816_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=gameViewer.models.get_upload_path),
        ),
    ]
